# Generated by Django 5.2.14 on 2026-06-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancesubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
