# Generated by Django 5.2.14 on 2026-06-14 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_insurancesubscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='eligibility_score_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREDIT_STATUS_CHANGE', 'Changement de statut de crédit'), ('PAYMENT_RECORDED', 'Paiement enregistré'), ('CHAT_JOINED', 'Conversation rejointe'), ('CHAT_ASSIGNED', 'Conversation assignée'), ('USER_TOGGLED', 'Compte utilisateur activé/désactivé'), ('USER_CREATED', 'Utilisateur créé par admin')], max_length=30)),
                ('target_model', models.CharField(blank=True, help_text='Modèle concerné (ex: LoanRequest, Payment).', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text="ID de l'objet concerné.", null=True)),
                ('description', models.TextField(help_text="Description lisible de l'action effectuée.")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text="L'agent ou l'admin qui a effectué l'action.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
