# Generated by Django 5.2.14 on 2026-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loanrequest_eligibility_score_detail_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur (JPEG/PNG, max 5 Mo recommandé).", null=True, upload_to='avatars/'),
        ),
    ]
