# Generated by Django 5.2.14 on 2026-06-15 18:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymentinstallment',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pénalités de retard accumulées (1 % par jour sur le solde impayé).', max_digits=12),
        ),
    ]
